name: A workflow for lighthouse action
on: push
jobs:
    lighthouse_action:
      name: lighthouse action
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: run lighthouse
          run: chmod +x ./script.sh && ./script.sh
          

